### ISSUE TITLE
运行USTCRVSoC-tool时发生错误

### ISSUE THREAD

**Issue by zchliu** [WangXuan95/USTCRVSoC#6]
![1](https://user-images.githubusercontent.com/55781450/156979602-661f7ee4-75ce-461d-be3f-b3d1610c69b3.png)
按照文中说的点击汇编按钮以后出现错误，想问一下要如何解决。用的是vs2019进行build。

**Comment by WangXuan95** [comment]
字面意思，需要把工具链目录 (在我的库的 tools 目录下的 riscv32-elf-tools-windows 这个目录) 拷贝到 USTCRVSoC-tool.exe 所在的目录下。

另外，不用你自己编译，直接运行我编译好的 USTCRVSoC-tool.exe 就行了。它就在 tools 目录下。

**Comment by zchliu** [comment]
解决了，谢谢！
