### ISSUE TITLE
请问是普林斯顿架构还是哈佛架构

### ISSUE THREAD

**Issue by david4958606** [WangXuan95/USTCRVSoC#8]
开发者您好：

您在 README 中说
> 一个 SystemVerilog 编写的，以一个 RISC-V CPU 为核心的，普林斯顿结构的 SoC

但是您下文给的图片却是指令存储和数据存储分开的哈佛架构，请问这里是否有笔误呢？

**Comment by WangXuan95** [comment]
我这个就是普林斯顿架构。
普林斯顿还是哈佛，不是看在物理上把指令和数据放在同一个还是不同的存储器里，而是看逻辑上是否区分指令和数据的地址空间。像我这种架构，使用同一个地址空间，因此同一时刻指令和数据必须放在不同地址，否则就地址冲突了。而哈佛架构可以让指令的地址和数据地址相同，因为根本就是两片空间，不会冲突。另外，普林斯顿架构里，因为共用存储空间，所以任何地方都可以放指令，也可以放数据，比如我的指令RAM里可以放数据，数据RAM里也可以放指令，也可以都放在指令或数据RAM里，因为CPU的指令和数据接口是共享总线的。我只不过是在物理上划分出两个RAM，推荐你把指令放在指令RAM，数据放在数据RAM，是为了防止总线争用，提升性能。

**Comment by david4958606** [comment]
好的，我明白了，感谢作者解读。
